New: Healthy check and prod construction

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -78,3 +78,31 @@ jobs:
           TF_VAR_port: 3001
           TF_VAR_environment: "dev"
           TF_VAR_environment_variables: '{"NODE_ENV": "development"}'
+          TF_VAR_CPU: 1
+          TF_VAR_RAM: 2
+
+      - name: Verify Application Health (Dev)
+        run: |
+            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://dev-app-url/health)
+            if [ "$RESPONSE" -ne 200 ]; then
+              echo "Application health check failed with status code $RESPONSE"
+              exit 1
+            else
+              echo "Application is healthy"
+            fi
+
+      - name: Deploy to AWS AppRunner (Prod)
+        run: |
+            cd terraform/prod
+            terraform init
+            terraform plan
+            terraform apply -auto-approve
+        env:
+          TF_VAR_service_name: "my-app-prod"
+          TF_VAR_image_identifier: "${{ steps.build-docker-image.outputs.image }}"
+          TF_VAR_access_role_arn: ${{ secrets.APPRUNNER_ROLE }}
+          TF_VAR_port: 3001
+          TF_VAR_environment: "prod"
+          TF_VAR_environment_variables: '{"NODE_ENV": "production"}'
+          TF_VAR_CPU: 2
+          TF_VAR_RAM: 4
